language: java
jdk:
  - oraclejdk8
before_install:
  - if [ ! -z "$GPG_SECRET_KEYS" ]; then echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import; fi
  - if [ ! -z "$GPG_OWNERTRUST" ]; then echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust; fi
install:
  - mvn --settings .travis/settings.xml validate -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V
script: mvn help:system
deploy:
  -
    provider: script
    skip_cleanup: true
    script: ./deploy.sh
    on:
      branch: master
      jdk: oraclejdk8
  -
    provider: script
    script: ./deploy.sh
    skip_cleanup: true
    on:
      tags: true
      jdk: oraclejdk8